### ISSUE TITLE
Running the script breaks landing pages split-image block

### ISSUE THREAD

**Issue by artoftheblue** [jupyter-book/book-theme-tailwind-quickstart#1]
Trying to integrate Tailwind CSS into my project, I've encountered a weird issue: the split-image block breaks after I run the script. Gladly, I've found the culprit: when the `output.css` file is generated, this CSS part is responsible for the misalignments, and removing it fixes the issue.

```css
.relative {
    position: relative
}

.absolute {
    position: absolute
}
```

> _Tbh, I am not sure why it is generated in the first place._
